### ISSUE TITLE
Travis is flaky

### ISSUE THREAD

**Issue by seanmcl** [typelevel/paiges#119]
I've recently had regular timeout failures on Travis.

E.g. https://travis-ci.org/typelevel/paiges/builds/412942735?utm_source=github_status&utm_medium=notification

The error is always

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something 
wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
```

I usually just re-push and the next time it completes fine.  Is this a known issue with Travis that users just live with?

**Comment by johnynek** [comment]
it is flaky. I don't know what to do about it. I can restart some of the builds on the travis page so you don't need to push, but push works too.

I assume it is because sometimes some of the laws create very slow to test properties and javascript is slower, so we notice at that point.

Maybe we can fix by turning down the number of trials on JS or finding the slow property?

**Comment by seanmcl** [comment]
Maybe this is too naive, but would it work to just do some `println`s?  It seems to care about output.

**Comment by johnynek** [comment]
If we knew which test, we could. It already prints after each test.

Running locally over and over with JS we would probably find it.

**Comment by seanmcl** [comment]
When I run locally, it pauses right at the beginning with the following:

```
[info] Done compiling.
[info] Fast optimizing /Users/seanmcl/Dropbox/sean/src/third_party/paiges/core/.js/target/scala-2.12/paiges-core-test-fastopt.js
(node:48129) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:48131) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[info] PaigesScalacheckTest:
[info] - (x = y) -> (x.## = y.##)
[info] - concat is associative
...
```

That is, before it spits out any input, it fast-optimizes for a long time.  Once tests start, they all complete quickly.  The second time I run `test` it doesn't do the `Fast optimizing`, and thus completes much faster.  I've never had a re-push fail, so perhaps it's this compilation step that is timing out, rather than some individual test.

**Comment by seanmcl** [comment]
Hmm, that doesn't seem right either.  I caught one on Travis stuck there, but there was a lot of output already, e.g. compilation steps.  In the failures the log is always empty, it doesn't just stop where the tests start.
