### ISSUE TITLE
Request new release to support Scala Native 0.3.x

### ISSUE THREAD

**Issue by ekrich** [typelevel/paiges#138]
Reference: https://github.com/typelevel/paiges/pull/87
This will also include other valuable updates since the last release.

**Comment by johnynek** [comment]
yeah. Thanks for the ping....

We do need to publish... We've been a bit underwater...

We really need a typelevel-wide CI publishing system so it doesn't tax maintainers.

**Comment by ekrich** [comment]
I just got started publishing myself so I'm aware of the overhead. We are appreciative of your willingness to help. cc/ @olafurpg

**Comment by larsrh** [comment]
@johnynek I can run a release if you like.

**Comment by johnynek** [comment]
I would deeply appreciate that.

It would be interesting to collaborate to build a typelevel auto publisher that publishes all tagged GitHub releases.

**Comment by olafurpg** [comment]
FWIW, I created a plugin sbt-ci-release (https://github.com/olafurpg/sbt-ci-release) that I use for most of my projects to release on tag push. I can recommend this setup!

**Comment by larsrh** [comment]
Looks like this worked! 0.2.2 with native support out now.

**Comment by olafurpg** [comment]
Grab it while it's hot!

```
coursier fetch org.typelevel:paiges-core_2.12:0.2.2 -r sonatype:public
```

**Comment by johnynek** [comment]
Thanks so much for the help folks!
