### ISSUE TITLE
ci-release is failing since sbt 1.3.5

### ISSUE THREAD

**Issue by larsrh** [typelevel/paiges#213]
Failure starts after #211. The only thing that changed is sbt 1.3.4 → 1.3.5, and suddenly the cross configuration (2.11 only) for the native build is ignored (sbt-ci-release tries to release 2.12 for native).

**Comment by olafurpg** [comment]
This looks like a regression sbt, ci-release is an alias for “+publish” for non-tagged commits.

**Comment by olafurpg** [comment]
This PR here could be related https://github.com/sbt/sbt/pull/5265
