### ISSUE TITLE
Scala 3.0.0-M2 release

### ISSUE THREAD

**Issue by SystemFw** [typelevel/paiges#313]
Paiges is awesome! Any chance of a release for Scala 3 M2 anytime soon? :)

**Comment by johnynek** [comment]
I am assuming M3 is acceptable. I think it is a bit much work for this project to publish for multiple versions of scala 3 at the moment, so I will stick to the latest version.

**Comment by johnynek** [comment]
welp, given the CI failures in #316 and #315 I think this didn't work.

Looking at the ci.yml, I also don't see scala 3 being tested.

So, it maybe that both the publishing failed and the CI isn't really running for scala 3.

Oh well...

It seems, as usual, that build work is needed.

cc @larsrh or @mpilquist who have in the past shown interest in doing this kind of work.

**Comment by SystemFw** [comment]
I think the problem (or one of the problems) is here
https://github.com/typelevel/paiges/blob/master/build.sbt#L7

Scala 3 is not in crossScalaVersion, which means it won't be part of the build matrix, so it's not getting built, and probably wasn't published either (I'll check)

**Comment by johnynek** [comment]
Looks like even the 2.13 wasn't published.

**Comment by SystemFw** [comment]
> Scala 3 is not in crossScalaVersion, which means it won't be part of the build matrix,

I've confirmed this to be one of the issues

> Looks like even the 2.13 wasn't published.

yeah, weird

**Comment by larsrh** [comment]
Delegating this to @djspiewak 😉

**Comment by djspiewak** [comment]
I'm not sure why the Scala version matters to `ci-release`. It *should* just cross-publish everything, if I'm understanding the plugin correctly. Paging @olafurpg if he has a moment.

**Comment by olafurpg** [comment]
`ci-release` runs `+publishSigned`, which depends on `crossScalaVersions`. You can run `+publishLocal` to manually test how the matrix looks like in the build. 

The line here looks suspicious 

https://github.com/typelevel/paiges/blob/5e5b6a955697360fe7425515ac4de4514ea2bdd6/.github/workflows/ci.yml#L119

I normally copy-paste the same `release.yml` between my projects, which you can try to adapt to this repo https://github.com/olafurpg/sbt-ci-release/blob/master/.github/workflows/release.yml

**Comment by olafurpg** [comment]
You can BTW add the following environment variables to customize the publish commands

```
CI_SNAPSHOT_RELEASE=publish
CI_RELEASE=publishSigned
```

**Comment by johnynek** [comment]
So, I see this:

https://github.com/typelevel/paiges/runs/1773121666?check_suite_focus=true#step:5:216

where it says it has no access to secrets, doing nothing, but the script thinks it has been successful (the task is green, not red).

**Comment by olafurpg** [comment]
I can't remember exactly why `ci-release` plugin silently skips the release when secrets are missing. I recall vaguely that this behavior is intentional since it simplified the Yaml configuration at some point with Travis CI (you can always run `ci-release`, even in pull requests where secrets are missing). I'm not sure I would choose this behavior today.

Either way, adding the secrets according to https://github.com/olafurpg/sbt-ci-release/#secrets should fix the problem.

**Comment by olafurpg** [comment]
BTW, it's possible to add organization-wide secrets. This would avoid the need to manually configure Sonatype/GPG secrets for every new repo.

**Comment by johnynek** [comment]
I'm confused what changed. This used to work. @larsrh any ideas? I thought we did have org wide secrets for typelevel?

**Comment by olafurpg** [comment]
There appears to have been a regression in https://github.com/typelevel/paiges/commit/e9dac783160ea5e436f02bc2ef312607ac346900 where the `ci-release` step is missing the environment variables that are declared here https://github.com/olafurpg/sbt-ci-release/blob/1df0e7aeb75e1d5a2bf086cc53658c6d3e680850/.github/workflows/release.yml#L15-L20

I opened https://github.com/typelevel/paiges/pull/321 adding the `release.yml` file I use in all of my projects. I haven't used sbt-github-action myself but I suspect you can achieve something similar with it

**Comment by johnynek** [comment]
I tried merging #321 

I'm seeing some error about too many redirects:

https://github.com/typelevel/paiges/runs/1787866793

which I don't know if that is due to some authentication issue that is causing a redirect or something else.

**Comment by olafurpg** [comment]
I have hit in the same redirect error and I think it’s a sonatype issue. I would try to release again another day. Also make sure the version you release hasn’t been published before (I occasionally get cryptic errors when this happens)

**Comment by SystemFw** [comment]
Sonatype was down a few days ago fyi, and I had to delay some releases, so not unlikely there is a problem on their side

**Comment by larsrh** [comment]
0.4.0 is out, I released it manually.

**Comment by johnynek** [comment]
Thanks everyone!
