### ISSUE TITLE
Enable coverage after plugin is released for 2.12.13

### ISSUE THREAD

**Issue by ekrich** [typelevel/paiges#341]
In the Scala Native PR https://github.com/typelevel/paiges/pull/338, coverage was disabled due to the plugin not supporting Scala `2.12.13` which is the only `2.12` version that Scala Native `0.4.0` supports.

The `sbt-coverage` issue is being tracked here: https://github.com/scoverage/sbt-scoverage/issues/319

**Comment by johnynek** [comment]
this may be fixed now by #347 

@ekrich would you have a bit of time to try to update?

**Comment by ekrich** [comment]
Sure if I can remember how.

**Comment by ekrich** [comment]
@johnynek There is some updating needed for `build.sbt`. Now that the project is on version `1.5.0+`, `sbt-dotty` is no longer needed, and changes should be made for unified slash syntax - giving warnings now.
