### ISSUE TITLE
Doubt regarding Documentation

### ISSUE THREAD

**Issue by shankarshastri** [typelevel/paiges#371]
Was going through README.md, saw this one:
Competitive performance (e.g. 3-5x **slower** than `mkString`) is it slower or faster?

**Comment by johnynek** [comment]
It's slower. mkString is the upper bound: you are very unlikely to beat that.

But this code 1. is lazy (it renders on demand) and 2. optimizes where to put new lines in cases where new line or space will do.

So it is doing a lot more than mkString, so getting at all in the same ballpark while doing much more is very good.

**Comment by shankarshastri** [comment]
Closing this issue, as it's not a issue !!
