### ISSUE TITLE
Idiomatic way to nudge elements to the same level of nesting

### ISSUE THREAD

**Issue by morgen-peschke** [typelevel/paiges#388]
I'm looking into pretty-printing some object graphs, and I'd love to use paiges to handle the rendering because the width is going to vary dynamically, based on terminal width etc.

I'm running into a bit of difficulty with how arrays and maps are wrapped. I'm curious if there's something I'm missing which would enable keeping sibling elements on the same level.

It's easiest to see the impact with maps. I'm currently here:
```
{
  1 -> {2 -> a}, 3 -> {
                     4 -> b, 5
                               ->
                               c
                   }, 6 -> {
                          7 ->
                            c
                        }
}
```
And I'd like to get closer to here:
```
{
  1 -> {2 -> a},
  3 -> {
         4 -> b,
         5 -> c
       },
  6 -> {7 -> c}
}
```
This would be even better: 
```
{
  1 -> {2 -> a},
  3 -> {
    4 -> b,
    5 -> c
  },
  6 -> {7 -> c}
}
```

I've simplified down my code which creates `Doc`s from arrays:
```scala
import org.typelevel.paiges.Doc

// This is a simplified version of what I'm using to recurse into the object graph.
// Other than that, it's irrelevant.
trait Convertible[A, B] {
  def convert(value: A): B
}

// Using List[Int] for simplicity, the elements can be arbitrarily nested object graph of maps, arrays, scalars, etc.
implicit val intToDoc: Convertible[Int, Doc] = i => Doc.text(s"$i")
implicit def listToDoc[A](implicit A: Convertible[A, Doc]): Convertible[List[A], Doc] =
  la => Doc.intercalate(Doc.char(',') + Doc.lineOrSpace, la.map(A.convert))

val flat = implicitly[Convertible[List[Int], Doc]].convert {
  List(1, 2, 3, 4, 5)
}

println(flat.render(15))
println("-" * 15)
println(flat.render(10))
println("-" * 15)
println(flat.render(3))
```
[Scastie](https://scastie.scala-lang.org/Mw9SFVRfQueDyf9c4gJN1A)

Outputs:
```
1, 2, 3, 4, 5
---------------
1, 2, 3,
4, 5
---------------
1,
2,
3,
4,
5
```
I didn't see a way to make `render(10)` behave like `render(3)`, at least based on what's in `Doc`. Am I missing something?

**Comment by johnynek** [comment]
Sorry I don't have time to write the code fully out, but I think you are missing `Doc.grouped`.

What `.grouped` does is flatten the whole thing, or not at all.

So, what I recommend is write the shape you want with new lines (make sure you see `lineBreak` as well as `line` to decide which kinds of newline flattening you want), and then end finally `.grouped` the result, optionally.

Or, you can use `.grouped` when you recurse inside the map, but not use `.grouped` on the result of the map.

Does that make sense?

**Comment by morgen-peschke** [comment]
I think so.

The method description for `grouped` doesn't really convey that aspect of how it affects the result. Is there a user guide I missed?

**Comment by morgen-peschke** [comment]
It looks like the issue was too many `.grouped`, rather than missing them.

I realized it was silly to use "sort of JSON" as an example, and I should just use Json4s's AST and be done with it, so that was my bad, sorry for the sub-optimal example in the OP. Anyway, I put together a _much_ simpler example that showcases the behavior in a way that's hopefully much easier to follow:
```
import org.typelevel.paiges.Doc
import org.json4s.JsonAST._

val lineStyle = Doc.line

def renderJValueToDoc(jValue: JValue): Doc = {
  
  def array(values: List[JValue]): Doc =
    if (values.isEmpty) Doc.text("[]")
    else
      Doc
        .intercalate(Doc.comma + lineStyle, values.map(renderJValueToDoc))
        .tightBracketBy(Doc.char('['), Doc.char(']'))

  def string(str: String): Doc = Doc.char('"') + Doc.text(str) + Doc.char('"')

  jValue match {
    case JNothing      => Doc.empty
    case JNull         => Doc.text("null")
    case JString(s)    => string(s)
    case JDouble(num)  => Doc.str(num)
    case JDecimal(num) => Doc.str(num)
    case JLong(num)    => Doc.str(num)
    case JInt(num)     => Doc.str(num)
    case JBool(true)   => Doc.text("true")
    case JBool(false)  => Doc.text("false")
    case JArray(arr)   => array(arr)
    case JSet(set)     => array(set.toList)
    case JObject(obj) =>
      if (obj.isEmpty) Doc.text("{}")
      else
        Doc
          .intercalate(
            Doc.comma + lineStyle,
            obj.map { case (key, value) =>
              string(key) & Doc.char('=') & renderJValueToDoc(value)
            }
          )
          .tightBracketBy(Doc.char('{'), Doc.char('}'))
  }
}
```

The difference comes down to `Doc.line` vs `Doc.lineOrSpace`. I'd been using `lineOrSpace` because I thought the two were basically equivalent, and `lineOrSpace` felt more intentional.

Using `lineOrSpace` (or `line.grouped`), at width 20:
```
{
  "a" = 34, "b" = {
    "b0" = 1,
    "b1" = [
      true, false
    ], "b3" = 3
  },
  "c" = "This is a test",
  "d" = [[true]],
  "e" = {
    "e0" = "Second level: prop 0",
    "e1" = true,
    "e2" = 4,
    "e3" = "Second level: prop 3"
  }, "f" = null,
  "g" = 4
}
```
Using `line`:
```
{
  "a" = 34,
  "b" = {
    "b0" = 1,
    "b1" = [
      true,
      false
    ],
    "b3" = 3
  },
  "c" = "This is a test",
  "d" = [[true]],
  "e" = {
    "e0" = "Second level: prop 0",
    "e1" = true,
    "e2" = 4,
    "e3" = "Second level: prop 3"
  },
  "f" = null,
  "g" = 4
}
```

I used this snippet to print out all the variants of a test object, which was really helpful to understand what was going on:
```
import org.json4s.JsonDSL._

def json(v: JValue): JValue = v
def arr(values: JValue*): JValue = JArray(values.toList)
def obj(fields: (String, JValue)*): JObject = JObject(fields.toList)

val doc = renderJValueToDoc(obj(
  "a" -> 34,
  "b" -> obj("b0" -> 1, "b1" -> arr(true, false), "b3" -> 3),
  "c" -> "This is a test",
  "d" -> arr(arr(true)),
  "e" -> obj(
    "e0" -> "Second level: prop 0",
    "e1" -> true,
    "e2" -> 4,
    "e3" -> "Second level: prop 3"
  ),
  "f" -> JNull,
  "g" -> 4
))

(1 to doc.maxWidth).foldLeft("") { (prev, width) => 
  val curr = doc.render(width)
  if (curr == prev) prev
  else {
    println((Doc.char('-').repeat(20).space("Width:") & Doc.str(width) & Doc.char('-').repeat(100)).render(130))
    println(curr)
    curr
  }
}
```
[Scastie](https://scastie.scala-lang.org/udGVkA3WTU6hm0eW2knYgg)
