### ISSUE TITLE
Cut a release supporting Scala 3 Native

### ISSUE THREAD

**Issue by floating-cat** [typelevel/paiges#515]
Hi,
It seems in this [PR](https://github.com/typelevel/paiges/pull/504), this library starts to support the Scala 3 Native.
Can you cut a release for it?
I am trying to make the [metaconfig](https://github.com/scalameta/metaconfig) work for Scala 3 Native which depends on this library.
Thanks.

**Comment by johnynek** [comment]
I'm traveling right now but this is a good idea. Sorry we didn't do it sooner.

I will do this in the next few days.

**Comment by DamianReeves** [comment]
Just a friendly bump on this as it would be great to get a Scala 3 Scala Native version

**Comment by armanbilge** [comment]
There are snapshots available until a maintainer can make a release, hopefully soon :)

https://s01.oss.sonatype.org/content/repositories/snapshots/org/typelevel/paiges-core_native0.4_3/0.4.2-117-cefdfbc-SNAPSHOT/

**Comment by DamianReeves** [comment]
Thanks. Snapshot is a temporary stop gap as I'm pulling it in, in an environment that uses Artifactory to catch cache packages and it doesn't cache snapshots

**Comment by armanbilge** [comment]
polite ping @typelevel/paiges :)

**Comment by johnynek** [comment]
I'll publish this weekend.

**Comment by johnynek** [comment]
https://github.com/typelevel/paiges/releases/tag/v0.4.3

I have tagged this and it should build.

Let's see.

Honestly, I don't remember how this one publishes... I think it is set up to automatically go out when a tag is pushed.

**Comment by johnynek** [comment]
looks like it worked:

https://github.com/typelevel/paiges/actions/runs/5371969311/jobs/9745094548

**Comment by armanbilge** [comment]
artifacts are live
https://repo1.maven.org/maven2/org/typelevel/paiges-core_native0.4_3/0.4.3/
