### ISSUE TITLE
Readme example does not compile

### ISSUE THREAD

**Issue by lihaoyi** [typelevel/paiges#61]
```scala
lihaoyi ~$ amm
Loading...
Welcome to the Ammonite Repl 0.8.5
(Scala 2.12.2 Java 1.8.0_112)
If you like Ammonite, please support our development at www.patreon.com/lihaoyi
@ interp.load.ivy("org.typelevel" %% "paiges-core" % "0.1.0")

@ import org.typelevel.paiges._
import org.typelevel.paiges._
@ def mkCaseClass(name: String, fields: (String, String)*): Doc = {
    val prefix = Doc.text("case class ") + Doc.text(name) + Doc.char('(')
    val suffix = Doc.char(')')
    val types = fields.map { case (k, v) =>
      Doc.text(k) + Doc.char(':') + Doc.space + Doc.text(v)
    }
    val body = Doc.intercalate(Doc.char(',') + Doc.line, types)
    body.tightBracketBy(prefix, suffix)
  }
cmd2.sc:8: value tightBracketBy is not a member of org.typelevel.paiges.Doc
  body.tightBracketBy(prefix, suffix)
       ^
Compilation Failed
```

Not sure if `tightBracketBy` forgot to make it into the public release, or whether it was removed earlier, but it definitely doesn't exist right now

`bracketBy` does, but that inserts spaces inside the parens which isn't what I want

**Comment by lihaoyi** [comment]
Seems like a viable user-land implementation is

```scala
def bracketBy(self: Doc, left: Doc, right: Doc, indent: Int = 2): Doc =
    left + ((Doc.lineBreak + self).nested(indent) + (Doc.lineBreak + right)).grouped
```

**Comment by johnynek** [comment]
Yes, you can work around in userland. That method was added after 0.1.0.

We can publish soon with that present.

**Comment by lihaoyi** [comment]
Cool thanks!

**Comment by seanmcl** [comment]
When is the next release planned to hit maven central?  Thanks!

**Comment by coltfred** [comment]
@johnynek @non I can try and publish 0.2 today, but I don't know if I have permission to push to this project on sonatype. I certainly do for other typelevel projects, but I'm not sure what level of control they have on that. Do either of you have a problem with that?

**Comment by johnynek** [comment]
@coltfred sounds great. DO IT! :)

only typelevel permissions are needed.

Thank you so much!

**Comment by coltfred** [comment]
I published 0.2.0, which is on sonatype and I *think* it's on its way to central, but it's been a while since I've messed with sonatype so I might have messed up something. Let me know if you don't see it soon, I'm heading to bed now.

**Comment by seanmcl** [comment]
It's in maven central now. Thanks!

**Comment by coltfred** [comment]
Awesome! Let me know if there are any other problems.

**Comment by johnynek** [comment]
Thanks @coltfred !
