### ISSUE TITLE
Missing benchmark jar for 0.2.0

### ISSUE THREAD

**Issue by seanmcl** [typelevel/paiges#65]
Importing paiges is failing due to a missing jar, paiges-benchmark.  I don't see it (for any version) on maven central.  I tried both 0.1.0 and 0.2.0.  

Added to my build.sbt dependencies:

    "org.typelevel"  %% "paiges"  % "0.2.0"

Things I tried:

 - running the benchmarks at master in the paiges repo (they work)
 - looking in pom files on maven central (no mention of benchmark)
 - looking in the ivy cache xml files (e.g. ivy-0.2.0.xml, shows the benchmark dependency)

I don't have experience packaging Scala libraries, so am not sure how the pom file gets translated into the ivy xml file with the dependency.  Any idea how I can fix this?

```
warn] 	module not found: org.typelevel#paiges-benchmark_2.12;0.2.0
[warn] ==== local: tried
[warn]   /Users/seanmcl/.ivy2/local/org.typelevel/paiges-benchmark_2.12/0.2.0/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/typelevel/paiges-benchmark_2.12/0.2.0/paiges-benchmark_2.12-0.2.0.pom
[warn] ==== sonatype-releases: tried
[warn]   https://oss.sonatype.org/content/repositories/releases/org/typelevel/paiges-benchmark_2.12/0.2.0/paiges-benchmark_2.12-0.2.0.pom
[warn] ==== jcenter: tried
[warn]   https://jcenter.bintray.com/org/typelevel/paiges-benchmark_2.12/0.2.0/paiges-benchmark_2.12-0.2.0.pom
[info] Resolving jline#jline;2.14.1 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.typelevel#paiges-benchmark_2.12;0.2.0: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
```

**Comment by johnynek** [comment]
you should import `paiges-core` that should fix things. We should probably not publish `paiges` or exclude `paiges-benchmark` explicitly.

**Comment by johnynek** [comment]
note the badge links correctly:

https://index.scala-lang.org/typelevel/paiges/paiges-core

**Comment by seanmcl** [comment]
Ah, thanks!
