### ISSUE TITLE
renderTrim did not work as expected for me.

### ISSUE THREAD

**Issue by oscar-stripe** [typelevel/paiges#78]
I have a document with trailing white-space. I expected it to be identical to removing the trailing whitespace. I didn't get that.

I'll try to make a test of the law I expect to be true for renderTrim (basically that it is the same as rendering, splitting on newlines, then removing all right-most whitespace).

cc @seanmcl

**Comment by seanmcl** [comment]
Hi Oscar,

Could you please attach some code that reproduces the bug?  Happy to tal. 

Sean

**Comment by seanmcl** [comment]
Thanks.  Your law was not quite what I had in mind when I wrote it.  PR in the works.

**Comment by seanmcl** [comment]
Have a first cut working: #80
