### ISSUE TITLE
Missing artifact for paiges-cats 0.2.0 for Scala 2.11

### ISSUE THREAD

**Issue by andyscott** [typelevel/paiges#83]
It looks like the paiges-cats 0.2.0 artifact wasn't published for Cats 2.11: https://mvnrepository.com/artifact/org.typelevel/paiges-cats

**Comment by andyscott** [comment]
Additionally there's a tag for 0.1.0 but not for 0.2.0. Maybe the release process failed at the very end?

**Comment by johnynek** [comment]
Sounds totally fine to me. Sorry for the failed publish.

**Comment by andyscott** [comment]
@johnynek you can just count this as another reason for needing source dependencies 😄.

**Comment by johnynek** [comment]
I don’t need any extra reasons. ;)

**Comment by coltfred** [comment]
@andyscott 0.2.1 is on Sonatype. Should sync soon. I'll close this once I verify.

**Comment by coltfred** [comment]
https://repo1.maven.org/maven2/org/typelevel/paiges_2.12/0.2.1/ -- It's out there. The search will catch up shortly. Thanks for bringing this up, Andy.

**Comment by andyscott** [comment]
Thanks you for the quick fix!
