### ISSUE TITLE
Add support for annotations

### ISSUE THREAD

**Issue by seanmcl** [typelevel/paiges#91]
Adding annotations would be a nice feature, e.g. terminal output color codes.

http://hackage.haskell.org/package/prettyprinter-1.2.1/docs/Data-Text-Prettyprint-Doc.html#g:14
http://hackage.haskell.org/package/prettyprinter-1.2.1/docs/Data-Text-Prettyprint-Doc-Render-Tutorials-TreeRenderingTutorial.html

I'm not sure the very large change required is worth it, but figured I'd see if anyone upvotes.

**Comment by non** [comment]
I like the idea of this. I guess the main challenge is that we'd have to support zero-width pieces of text correctly?

**Comment by johnynek** [comment]
closed by #184
